-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('VISIT_REQUEST', 'VISIT_APPROVED', 'VISIT_REJECTED', 'VISIT_COMPLETED', 'REVIEW_ADDED', 'FAVORITE_ADDED', 'PROPERTY_APPROVED', 'PROPERTY_REJECTED', 'GENERAL');

-- AlterTable
ALTER TABLE "Notification" ADD COLUMN     "type" "NotificationType" NOT NULL DEFAULT 'GENERAL';
